### ISSUE TITLE
checkIsRepo has confusing semantics

### ISSUE THREAD

**Issue by winny-** [steveukx/git-js#261]
When using `require('simple-git')` (non-promise version), `checkIsRepo()` takes a handler function that takes a possible error object and a boolean indicating if the repo exists. When using `require('simple-git/promise')`, `checkIsRepo()`'s `.then()` takes a boolean which will always be true, because `.catch()` would be used in the case the repo does not exist.

Wondering if it'd make sense to do away with the boolean since this appears to be simply the error object flattened into a boolean then inverted.

At any rate it appears the example on the npm package site for the promise version doesn't work because of what I outlined above.

**Comment by st-sloth** [comment]
The problem is not the semantics but the error in the code that causes a reject instead of returning `false` on some git versions. It is fixed in #264 but not yet merged.

**Comment by st-sloth** [comment]
Now it is merged and released.

**Comment by winny-** [comment]
Thanks for the clarification :). Closing.

**Comment by mittalyashu** [comment]
I am still facing this issue, does anyone know the fix about it.

```js
const validateGitRepository = git(path);
			console.log(validateGitRepository);
			const isGit = await validateGitRepository.checkIsRepo();
			try {
				console.log(isGit);
				return isGit;
			} catch (error) {
				console.log(error);
			}
```
